### ISSUE TITLE
Error - cannot read property 'codeinjection_head' of undefined

### ISSUE THREAD

**Issue by ocundale** [TryGhost/gatsby-source-ghost#18] opened 2019-11-08 12:52 UTC
I get the following error after simply adding the plugin to my 'gastby-config.js' file:

```javascript
{
      resolve: 'gatsby-source-ghost',
      options: {
        apiUrl: 'http://165.22.123.203/ghost',
        contentApiKey: 'af42a8bea1d7a6e1ef1a611193',
        version: 'v2',
      },
    },
```

Error output:
```
 ERROR #11321  PLUGIN

"gatsby-source-ghost" threw an error while running the sourceNodes lifecycle:

Cannot read property 'codeinjection_head' of undefined

  TypeError: Cannot read property 'codeinjection_head' of undefined
  
  - gatsby-node.js:99 
    [landing-page]/[gatsby-source-ghost]/gatsby-node.js:99:43
  
  - task_queues.js:89 processTicksAndRejections
    internal/process/task_queues.js:89:5
  
  - From previous event:
  
  - gatsby-node.js:120 createLiveGhostNodes
    [landing-page]/[gatsby-source-ghost]/gatsby-node.js:120:20
  
  - gatsby-node.js:155 Object.exports.sourceNodes
    [landing-page]/[gatsby-source-ghost]/gatsby-node.js:155:12
  
  - api-runner-node.js:234 runAPI
    [landing-page]/[gatsby]/dist/utils/api-runner-node.js:234:37
  
  - api-runner-node.js:347 Promise.catch.decorateEvent.pluginName
    [landing-page]/[gatsby]/dist/utils/api-runner-node.js:347:15
  
  - api-runner-node.js:346 
    [landing-page]/[gatsby]/dist/utils/api-runner-node.js:346:12
  
  - timers.js:439 processImmediate
    internal/timers.js:439:21
```

Versions:
Ghost Version:  2.31.1
Gatsby CLI version: 2.7.14
Gatsby version: 2.15.28
Gatsby Source Ghost Version: 4.01
Node Version: v12.3.1
OS: OSX Mojave

**Comment by AileenCGN** [comment] 2019-11-12 05:43
Your API URL is not correct. This needs to be without `/ghost`:

```
      resolve: 'gatsby-source-ghost',
      options: {
        apiUrl: 'http://165.22.123.203',
        contentApiKey: 'af42a8bea1d7a6e1ef1a611193',
        version: 'v2',
      }
```

Closing this as it's not a bug.

**Closed by AileenCGN** 2019-11-12 05:43 UTC

**Comment by AileenCGN** [comment] 2019-11-12 06:00
@ocundale Looked at the README, and you did nothing wrong, just the README stating something wrong! Sorry! I fixed the README now 😊
